### ISSUE TITLE
error after running recycle.py

### ISSUE THREAD

**Issue by OAF12** [rozovr/Recycler#14]
recycle.py -g assembly_graph.fastg -k 55 -b reads_pe_primary.sort.bam
I got the below erro
Traceback (most recent call last):
  File "/home/omnah486/miniconda2/bin/recycle.py", line 4, in <module>
    __import__('pkg_resources').run_script('recycler==0.6', 'recycle.py')
  File "/home/omnah486/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/omnah486/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/omnah486/miniconda2/lib/python2.7/site-packages/recycler-0.6-py2.7.egg/EGG-INFO/scripts/recycle.py", line 62, in <module>
    
AttributeError: 'module' object has no attribute 'AlignmentFile'

**Comment by rozovr** [comment]
This looks like a pysam related error. Please check pysam is installed properly.

**Comment by OAF12** [comment]
Thanks for your reply, I re-installed pysam. Now I got that below error:

Traceback (most recent call last):
  File "/home/omnah486/miniconda2/bin/recycle.py", line 4, in <module>
    __import__('pkg_resources').run_script('recycler==0.6', 'recycle.py')
  File "/home/omnah486/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/omnah486/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/omnah486/miniconda2/lib/python2.7/site-packages/recycler-0.6-py2.7.egg/EGG-INFO/scripts/recycle.py", line 69, in <module>
    
NameError: name 'get_fastg_digraph' is not defined

**Comment by sergiomorgado** [comment]
The same error here:
NameError: name 'get_fastg_digraph' is not defined

All dependencies are ok.

**Comment by rozovr** [comment]
Can you please me how you installed recycler? I.e., did you do git pull, download a zip, etc. and where from? That will help me diagnose why this happens.

**Comment by OAF12** [comment]
Hi,

I did non-bioconda install steps, following the instructions in https://github.com/Shamir-Lab/Recycler?


Best regards

Omneya

________________________________

**Comment by sergiomorgado** [comment]
I installed using conda.

**Comment by OAF12** [comment]
I found that some persons had a problem with recycler installed by bioconda then I installed non-bioconda and I did both.

https://github.com/Shamir-Lab/Recycler/issues/9

But still the final command is not working


 Best

Omneya

________________________________

**Comment by rozovr** [comment]
@OAF12 and @sergiomorgado , sorry for my delay, am wrapping up my thesis now; will look into this soon
