### ISSUE TITLE
Recycle.py: Runtime error

### ISSUE THREAD

**Issue by Freemacl** [rozovr/Recycler#17]
When I try to execute recycle.py, I get the following error:

Traceback (most recent call last):
  File "/home/imss/.local/bin/recycle.py", line 4, in <module>
    __import__('pkg_resources').run_script('recycler==0.62', 'recycle.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 738, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/imss/.local/lib/python2.7/site-packages/recycler-0.62-py2.7.egg/EGG-INFO/scripts/recycle.py", line 83, in <module>
    
  File "/home/imss/.local/lib/python2.7/site-packages/networkx-2.0b2-py2.7.egg/networkx/classes/digraph.py", line 535, in remove_nodes_from
    for n in nbunch:
  File "/home/imss/.local/lib/python2.7/site-packages/networkx-2.0b2-py2.7.egg/networkx/algorithms/isolate.py", line 94, in <genexpr>
    return (n for n, d in G.degree() if d == 0)
  File "/home/imss/.local/lib/python2.7/site-packages/networkx-2.0b2-py2.7.egg/networkx/classes/reportviews.py", line 367, in __iter__
    for n in self._nodes:
**RuntimeError: dictionary changed size during iteration**

System: Ubuntu Linux
For what it's worth, I was able to get everything up and running on my personal comp (mac osx), but I'm hoping to use this [unfortunately problematic] computer as it is much faster.

**Comment by rozovr** [comment]
Thanks. Are you sure all the dependencies are covered? How did you install?

**Comment by Freemacl** [comment]
MacOS (works): 
- numpy 1.12.1
- networkx 1.11
- pysam 0.11.2.2
- nose 1.3.7
- BWA 0.7.5a
- samtools 1.5
- SPAdes 3.10.1
none of the dependencies were met, so I installed with conda

Ubuntu (doesn't work):
- numpy 1.11.1
- networkx 2.0b2
- pysam 0.12
- nose 1.3.7
- BWA 0.7.12
- samtools 1.5
- SPAdes 3.10.1
Was only missing networkX, which I installed via pip

**Comment by salvoc81** [comment]
I was getting the same error on MacOS 10.12 (Sierra). Matching the versions of the module fixed the issue.

**Comment by rozovr** [comment]
Hi @salvoc81, do you mean the versions that are in the README? 
@Freemacl, sorry for my delay, am wrapping up my thesis now; will look into this soon

**Comment by nwatarai** [comment]
Hi, I got the same error, but downgraded Python networkX from 2.0 to 1.11 and the error disappeared.

**Comment by Freemacl** [comment]
@nwatarai @salvoc81 Thanks for the help! That fixed my issue. Phew.

**Comment by dpellow** [comment]
I got this as well. Fixed by changing line 83 of recycle.py:
G.remove_nodes_from(nx.isolates(G)) -->   G.remove_nodes_from(list(nx.isolates(G)))

See: http://pelegm-networkx.readthedocs.io/en/latest/reference/generated/networkx.algorithms.isolate.isolates.html

**Comment by dpellow** [comment]
Merged bug fix into master
