### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by JuanmaMedina** [rozovr/Recycler#22]
Good morning Shamir and community,

I am trying to apply Recycler over my SPAdes graph but I keep getting this error:

Traceback (most recent call last):
  File "/usr/local/home/lmt243/anaconda3/pkgs/recycler-0.6.2-py27_0/bin/recycle.py", line 70, in <module>
    G.remove_nodes_from(nx.isolates(G))
  File "/usr/local/home/lmt243/.local/lib/python2.7/site-packages/networkx-2.1-py2.7.egg/networkx/classes/digraph.py", line 555, in remove_nodes_from
    for n in nodes:
  File "/usr/local/home/lmt243/.local/lib/python2.7/site-packages/networkx-2.1-py2.7.egg/networkx/algorithms/isolate.py", line 94, in <genexpr>
    return (n for n, d in G.degree() if d == 0)
  File "/usr/local/home/lmt243/.local/lib/python2.7/site-packages/networkx-2.1-py2.7.egg/networkx/classes/reportviews.py", line 368, in __iter__
    for n in self._nodes:
RuntimeError: dictionary changed size during iteration

I know this error has been reported and closed before, but I have tried the solution described there and I still cannot solve this error (downgrading Python networkX from 2.0 to 1.11)

System: Ubuntu Linux

    numpy 1.14.0
    networkx 2.0
    pysam 0.11.2.2
    nose 1.3.7
    BWA 0.7.17
    samtools 1.7
    SPAdes 3.11.1

Recycler and these associated dependencies were installed through conda.

Thanks a lot in advance, if you need more info, please, drop me a line!

Best,
Juanma

UPDATE: Recycler seems to work installing the associated dependencies with conda and cloning the last version from here, as dpellow suggested. I did not updated before because the script is still running,may have got stuck at some point. But the script.py launches with no problem.

**Comment by dpellow** [comment]
Hi Juanma,

The latest update of Recycler should be compatible with networkx 2.0. Can you clone the latest update and let us know if you are still experiencing this problem?

Thanks

**Comment by dpellow** [comment]
This has been fixed -see discussion at issue #17
