### ISSUE TITLE
''Node not found'' issue

### ISSUE THREAD

**Issue by Ksalanin** [rozovr/Recycler#36]
Hi 

Im trying to use recycler for identifying circular elements from a mobilome (extracted plasmids from an environmental sample) 

when i run the command: recycle.py -g ../assembly_graph.fastg -k 127 -b reads_pe_primary.sort.bam -i False -o .

I get the error back after a little time: 

Traceback (most recent call last):
  File "/usr/local/bin/recycle.py", line 4, in <module>
    __import__('pkg_resources').run_script('recycler==0.62', 'recycle.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/recycler-0.62-py2.7.egg/EGG-INFO/scripts/recycle.py", line 173, in <module>

  File "build/bdist.linux-x86_64/egg/recyclelib/utils.py", line 340, in is_good_cyc
  File "build/bdist.linux-x86_64/egg/recyclelib/utils.py", line 324, in get_contigs_of_mates
  File "/usr/local/lib/python2.7/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 40, in has_path
    nx.shortest_path(G, source, target)
  File "/usr/local/lib/python2.7/dist-packages/networkx/algorithms/shortest_paths/generic.py", line 170, in shortest_path
    paths = nx.bidirectional_shortest_path(G, source, target)
  File "/usr/local/lib/python2.7/dist-packages/networkx/algorithms/shortest_paths/unweighted.py", line 223, in bidirectional_shortest_path
    raise nx.NodeNotFound(msg.format(source, target))
networkx.exception.NodeNotFound: Either source EDGE_10343701_length_848_cov_11.642164' or target EDGE_10682581_length_5431_cov_2.680430 is not in G

Thanks in advance for your help :)

**Comment by dpellow** [comment]
Thanks for the report, I believe the latest bug fix solved this issue. Please let us know if it has fixed the problem on your input files.
