### ISSUE TITLE
AttributeError: Digraph object

### ISSUE THREAD

**Issue by vappiah** [rozovr/Recycler#44]
Hi @dpellow 

I tried running the recycler with the command below and I got an error. Please advice

_recycle.py -g assembly_graph.fastg -k 50 -b ".mybam -o mydir_

**Error message**
143.506632 6899.693496211945 258.95512825000003
Traceback (most recent call last):
  File "/home/user/.local/bin/recycle.py", line 4, in <module>
    __import__('pkg_resources').run_script('recycler==0.62', 'recycle.py')
  File "/opt/apps/Python/Python-3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/apps/Python/Python-3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/home/user/.local/lib/python3.5/site-packages/recycler-0.62-py3.5.egg/EGG-INFO/scripts/recycle.py", line 100, in <module>
  File "/home/user/.local/lib/python3.5/site-packages/recycler-0.62-py3.5.egg/recyclelib/utils.py", line 205, in get_long_self_loops
AttributeError: 'DiGraph' object has no attribute 'nodes_with_selfloops'

**Comment by dpellow** [comment]
It's hard to tell without knowing more - how was Recycler installed? It looks like it is using Python3 even though Recycler is written in Python2. It seems like the problem is with the version of NetworkX - which version did you install?

By the way, we now recommend to use our [new tool SCAPP](https://github.com/Shamir-Lab/SCAPP) instead of Recycler.
