### ISSUE TITLE
error creating the BAM file

### ISSUE THREAD

**Issue by Niazevedo** [rozovr/Recycler#9]
Hi I'm trying to create the BAM file and it gives an error.
I have installed recycler using bioconda.

This is the error:

Danielas-Mac:Recycler niazevedo$ make_fasta_from_fastg.py -g assembly_graph1.fastg 
Traceback (most recent call last):
  File "/Users/niazevedo/anaconda/bin/make_fasta_from_fastg.py", line 4, in <module>
    __import__('pkg_resources').run_script('recycler==0.6', 'make_fasta_from_fastg.py')
  File "/Users/niazevedo/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/Users/niazevedo/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/Users/niazevedo/anaconda/lib/python2.7/site-packages/recycler-0.6-py2.7.egg/EGG-INFO/scripts/make_fasta_from_fastg.py", line 3, in <module>
    __requires__ = 'recycler==0.6'
  File "/Users/niazevedo/anaconda/bin/recycle.py", line 4, in <module>
    __import__('pkg_resources').run_script('recycler==0.6', 'recycle.py')
  File "/Users/niazevedo/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/Users/niazevedo/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/Users/niazevedo/anaconda/lib/python2.7/site-packages/recycler-0.6-py2.7.egg/EGG-INFO/scripts/recycle.py", line 5, in <module>
    
  File "/Users/niazevedo/anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: dlopen(/Users/niazevedo/anaconda/lib/python2.7/site-packages/pysam/libchtslib.so, 2): Library not loaded: @rpath/libhts.1.dylib
  Referenced from: /Users/niazevedo/anaconda/lib/python2.7/site-packages/pysam/libchtslib.so
  Reason: image not found

**Comment by rozovr** [comment]
It looks like an installation problem - have you tried the non-bioconda install steps?
